name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Your ideas help make Business Process Flow Viewer better for everyone.

  - type: dropdown
    id: type
    attributes:
      label: Type of request
      description: What type of feature is this?
      options:
        - New Feature - Something that doesn't exist yet
        - Enhancement - Improve existing functionality
        - New Design Style - A new BPF visualization style
        - UI/UX - Improve user interface or experience
        - Performance - Make things faster or more efficient
        - Integration - Connect with other tools/services
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when I can't see which BPF branch is active...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: |
        I would like to have a new design style that shows a timeline view with:
        - Horizontal timeline with dates
        - Duration between stages
        - Visual indicator for overdue stages
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I tried using the stepper design but it doesn't show timing information...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      description: Help us prioritize
      options:
        - Nice to have - Would be cool but not essential
        - Important - Would significantly improve my workflow
        - Critical - I really need this to use the tool effectively
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your use case. How would you use this feature?
      placeholder: |
        As a Dynamics 365 admin, I need to monitor sales pipeline progress.
        Having a timeline view would help managers see how long deals stay
        in each stage at a glance from the grid view.
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or examples
      description: If applicable, add mockups, screenshots, or examples from other tools.
      placeholder: Drag and drop images here or paste links to examples.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing?
      options:
        - label: I would be willing to help implement this feature
          required: false
        - label: I would be willing to test this feature
          required: false
